/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.bstats:bstats-bukkit:3.2.1")
    api("org.json:json:20251224")
    compileOnly("io.papermc.paper:paper-api:26.1.1.build.+")
}

group = "lol.hyper"
version = "1.0.10"
description = "hyperlib"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
